# basic-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: eks-sample-linux-app
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: eks-sample-linux-app
